# Section A: Functions

In [1]:
# Q.1
# write a function that takes two numbers as arguments and returns their sum.   
def add(a, b):
    return a + b
add(5, 3)

8

In [4]:
# Q.2
# write a function that accepts a list of numbers and returns the largest number in the list.
def find_largest(numbers):
    return max(numbers)
numbers = [3, 7, 2, 9, 5]
find_largest(numbers)

9

In [11]:
# Q.3
# create a function that checks whether a given number is even or odd.
def check_even_odd(num):
    if num % 2 == 0:
        return "Even"
    else:
        return "Odd"
check_even_odd(2.0)

'Even'

In [12]:
# Q.4 
# create a function that counts the number of vowels in a given string.
def count_vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

count_vowels("Hello, World!")

3

In [13]:
# Q.5
# create a function that calculates the factorial of a given number.
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

factorial(5)

120

In [16]:
# Q.6 
# write a function that accepts a student's marks and returns the grade according to the following criteria:
# 80 above: A+
# 70-79: A 
# 60-69: B
# 50-59: C
# below 50: F
def calculate_grade(marks):
    if marks >= 80:
        return "A+"
    elif marks >= 70:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"
calculate_grade(49)

'Fail'

In [20]:
# Q.7
# write a function that reverses a string without using bilt-in reverse methods.
def reverse_string(s):
    return s[::-1]
s = "Hello, World!"
reverse_string(s)

'!dlroW ,olleH'

In [21]:
# Q.8
# create a function that accepts a list and returns only the unique values from the list.
def unique_values(lst):
    return list(set(lst))
my_list = [1, 2, 3, 4, 2, 5, 1]
unique_values(my_list)

[1, 2, 3, 4, 5]

In [22]:
# Q.9 
# write a function that find the average of numbers stored in a list.
def average(numbers):
    return sum(numbers) / len(numbers)
numbers = [10, 20, 30, 40, 50]
average(numbers)

30.0

In [23]:
# Q.10
# Create a function that cheks whether a given word is a palindrome or not.
def is_palindrome(word):
    return word == word[::-1]
is_palindrome("madam")

True

# Section B: Pandas

In [34]:
# Q.1
# create pandas DataFrame with 3 columns: 'Name', 'Age', 'Marks' and 5 rows of data.
import pandas as pd
data = {
    'Name': ['Ali', 'Sara', 'Ahmed', 'Fatima', 'Hassan'],
    'Age': [25, 30, 35, 40, 45],
    'Marks': [85, 90, 95, 80, 75]
}
df.to_csv("students.csv", index=False)
df = pd.DataFrame(data)
df

     Name  Age  Marks
0     Ali   25     85
1    Sara   30     90
2   Ahmed   35     95
3  Fatima   40     80
4  Hassan   45     75

In [ ]:
# Q.2
# Load a CSV file named students.csv and display the first 5 rows.
import pandas as pd
df = pd.read_csv('students.csv')
df.head()

     Name  Age  Marks
0     Ali   25     85
1    Sara   30     90
2   Ahmed   35     95
3  Fatima   40     80
4  Hassan   45     75

In [36]:
# Q.3
# Find the total number of rows and columns in the DataFrame.
df.shape

(5, 3)

In [37]:
# Q.4
# Display only the 'Name' and 'Marks' columns from the DataFrame.
df[['Name', 'Marks']]

     Name  Marks
0     Ali     85
1    Sara     90
2   Ahmed     95
3  Fatima     80
4  Hassan     75

In [38]:
# Q.5
# Find students who marks are greater than 80.
df[df['Marks'] > 80]

    Name  Age  Marks
0    Ali   25     85
1   Sara   30     90
2  Ahmed   35     95

In [44]:
# Q.6
# add a new column called 'Grade' based on students marks.
def calculate_grade(marks):
    if marks >= 80:
        return "A+"
    elif marks >= 70:
        return "A"
    elif marks >= 60:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"
df['Grade'] = df['Marks'].apply(calculate_grade)
df

     Name  Age  Marks Grade
0     Ali   25     85    A+
1    Sara   30     90    A+
2   Ahmed   35     95    A+
3  Fatima   40     80    A+
4  Hassan   45     75     A

In [46]:
# Q.7
# Find the average marks of all students in the DataFrame.
avg_marks = df['Marks'].mean()
print("Average Marks:", avg_marks)

Average Marks: 85.0

In [67]:
# Q.8 
# Sort the DataFrame based on marks in descending order.
df_sorted = df.sort_values(by='Marks', ascending=False)
df_sorted

     Name  Age  Marks Grade
2   Ahmed   35     95    A+
1    Sara   30     90    A+
0     Ali   25     85    A+
3  Fatima   40     80    A+
4  Hassan   45     75     A

In [68]:
# Q.9
# Count the number of missing values in each column.
df.isnull().sum()

Name     0
Age      0
Marks    0
Grade    0
dtype: int64

In [ ]:
# Q.10
# Group students by Name and calculate the average salary/marks for each department.
df.groupby('Name')['Marks'].mean()

Name
Ahmed     95.0
Ali       85.0
Fatima    80.0
Hassan    75.0
Sara      90.0
Name: Marks, dtype: float64